services:
  - type: web
    name: pharmatrace-api
    runtime: docker
    rootDir: backend
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: COGNODB_URI
        sync: false
      - key: COGNODB_USERNAME
        value: cognodb
      - key: COGNODB_PASSWORD
        sync: false
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
      - key: PHARMATRACE_SEED_ENABLED
        value: "false"
