services:
  - type: web
    name: pharmatrace-web
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 22.13.0
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://pharmatrace-api-vev3.onrender.com

  - type: web
    name: pharmatrace-api
    runtime: docker
    rootDir: backend
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: COGNODB_URI
        sync: false
      - key: COGNODB_USERNAME
        value: cognodb
      - key: COGNODB_PASSWORD
        sync: false
      - key: APP_CORS_ALLOWED_ORIGINS
        value: https://pharmatrace-web.onrender.com
      - key: PHARMATRACE_SEED_ENABLED
        value: "false"
